// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a query a [`Neighbour`] shares, coarsely.
 *
 * A band and not the number, because the number invites a precision it
 * does not have: it is word overlap scaled by a ceiling nothing reaches,
 * so a duplicate reads as `0.4` and a reader takes that for "40% alike".
 * The cut-offs were read off a synthetic corpus of sixteen varied nodes:
 *
 * - word-for-word duplicates and promoted copies of a node scored
 *   `0.44`–`0.59` (one in a real corpus scored `0.36`), and
 *   sentences reusing most of a node's key words `0.28`–`0.53`;
 * - a sentence sharing one incidental word with a node scored
 *   `0.09`–`0.20`;
 * - a whole node against the others scored `0.07`–`0.13` for its topical
 *   neighbours and under `0.07` for nearly everything else.
 *
 * So [`Band::Strong`] starts at [`STRONG_FROM`], with margin under every
 * copy and over every one-word match, and [`Band::Weak`] ends at
 * [`SOME_FROM`], where a node's unrelated neighbours stop. Short queries score
 * higher for the same overlap, since one word is a larger share of two
 * than of twenty, so a one-word match on a two-word query can read
 * `strong`. The band ranks nothing; the order is still the score's.
 */
export type Band = "strong" | "some" | "weak";
