// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboxEntry } from "./InboxEntry";
import type { Neighbour } from "./Neighbour";

/**
 * A thought that has just gone into the inbox, and where it may belong.
 */
export type Captured = { 
/**
 * The entry as written.
 */
entry: InboxEntry, 
/**
 * Existing nodes the text reads closest to, best first, for the triage
 * that comes later. Empty when nothing shares a word with it, or when
 * the caller asked for none. A suggestion only: nothing here becomes
 * an edge, and the capture is in the inbox whatever this holds.
 */
near?: Array<Neighbour>, };
