// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";
import type { ObservatoryLink } from "./ObservatoryLink";

/**
 * A node with a reference newly attached.
 */
export type Cited = { 
/**
 * The node as written.
 */
doc: Doc, 
/**
 * The id of the reference that was added.
 */
reference: string, 
/**
 * Where the reference's record is on this machine, for an `observatory`
 * reference, and absent for every other kind. Its `path` is filled in by
 * [`Cited::with_observatory`], and is absent until a caller asks, as on
 * [`crate::graph::NodeView`], or when the record does not resolve.
 */
observatory?: ObservatoryLink | null, };
