// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";

/**
 * A node with a reference newly attached.
 */
export type Cited = { 
/**
 * The node as written.
 */
doc: Doc, 
/**
 * The id of the reference that was added.
 */
reference: string, };
