// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why and when a node left active work. Present only on refuted and
 * abandoned nodes; required, with a non-empty `why`, on refuted ones.
 */
export type Closed = { 
/**
 * What settled it. For a refuted node, how the kill condition fired.
 */
why: string, 
/**
 * When, as `YYYY-MM-DD`.
 */
at: string, };
