// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tag a write has just introduced that reads as a variant of one already
 * in use: the same label but for case or a trailing `s`.
 */
export type CloseTag = { 
/**
 * The tag as the write stored it.
 */
tag: string, 
/**
 * The tag already in use that it collides with, as written there.
 */
near: string, 
/**
 * How many nodes carry `near`.
 */
nodes: number, };
