// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A commit `neb` made after a write.
 */
export type Committed = { 
/**
 * The full commit hash.
 */
hash: string, 
/**
 * The message, `neb <verb> <ids>`.
 */
message: string, };
