// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the corpus is committed after each write, as `neb config commit`
 * reports it.
 */
export type CommitSetting = { 
/**
 * `commit` in `config.yaml`. `false` when the key is absent.
 */
enabled: boolean, };
