// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";
import type { Neighbour } from "./Neighbour";

/**
 * A node that has just been written for the first time.
 */
export type Created = { 
/**
 * The node as written.
 */
doc: Doc, 
/**
 * The file it went into.
 */
path: string, 
/**
 * Existing nodes the new one reads closest to, best first, for whoever
 * is deciding whether it has a parent. Filled by [`promote`] when no
 * parent was named; empty when one was, and always empty from
 * [`new_node`]. A suggestion only: nothing here becomes an edge.
 */
near?: Array<Neighbour>, };
