// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";

/**
 * A node that has just been written for the first time.
 */
export type Created = { 
/**
 * The node as written.
 */
doc: Doc, 
/**
 * The file it went into.
 */
path: string, };
