// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

/**
 * A node file: frontmatter plus the prose you actually wrote.
 */
export type Doc = { 
/**
 * Structured fields.
 */
node: Node, 
/**
 * The argument, the sketch, the thing you actually thought.
 */
body: string, };
