// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeType } from "./EdgeType";

/**
 * A typed link to another node.
 */
export type Edge = { 
/**
 * The relation this edge asserts.
 */
type: EdgeType, 
/**
 * The node id on the other end.
 */
to: string, };
