// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Edge kinds: the genealogy DAG plus one symmetric relation between ideas.
 */
export type EdgeType = "derives-from" | "refines" | "generalizes" | "reopens" | "contradicts";
