// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeType } from "./EdgeType";

/**
 * One edge, with both ends named, so the drawing does not have to look a
 * node up to know where an edge starts.
 */
export type EdgeRecord = { 
/**
 * The node the edge starts at.
 */
from: string, 
/**
 * The relation it asserts.
 */
type: EdgeType, 
/**
 * The node it points at.
 */
to: string, };
