// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * One violated invariant.
 */
export type Finding = { 
/**
 * Error or warning.
 */
level: Severity, 
/**
 * Which invariant, by its number in `docs/design/v0.2/1_spec.md`.
 */
rule: number, 
/**
 * The node it belongs to, where there is one.
 */
node: string | null, 
/**
 * What is wrong.
 */
message: string, };
