// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeRecord } from "./EdgeRecord";
import type { NodeSummary } from "./NodeSummary";

/**
 * The whole corpus as a drawable graph.
 */
export type GraphExport = { 
/**
 * Every node, in corpus order.
 */
nodes: Array<NodeSummary>, 
/**
 * Every edge, as declared, in node order.
 */
edges: Array<EdgeRecord>, };
