// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";
import type { Status } from "./Status";

/**
 * A node handed off to an Observatory record: cited and closed in one write.
 */
export type HandedOff = { 
/**
 * The node as written: `abandoned`, with the hand-off as its reason.
 */
doc: Doc, 
/**
 * The id of the `observatory` reference that was added.
 */
reference: string, 
/**
 * The record it went to, as stored: `H012`.
 */
record: string, 
/**
 * Where the node was before.
 */
from: Status, };
