// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One commit that changed a node.
 */
export type HistoryEntry = { 
/**
 * The full commit hash.
 */
hash: string, 
/**
 * The commit date, `YYYY-MM-DD`.
 */
date: string, 
/**
 * The commit's first-line message.
 */
message: string, };
