// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Touched } from "./Touched";

/**
 * What a node touches. Serializes as the bare list, descendants first.
 */
export type Impact = Array<Touched>;
