// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One unprocessed capture.
 *
 * Where the line lives is how [`Corpus::settle_inbox`] finds it again, and is
 * a detail of this corpus rather than part of the entry, so it stays out of
 * the serialized form.
 */
export type InboxEntry = { 
/**
 * Short id, unique within its file.
 */
id: string, 
/**
 * Capture timestamp.
 */
at: string, 
/**
 * What you wrote.
 */
text: string, };
