// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One unprocessed capture.
 *
 * Where the line lives is how [`Corpus::settle_inbox`] finds it again, and is
 * a detail of this corpus rather than part of the entry, so it stays out of
 * the serialized form.
 */
export type InboxEntry = { 
/**
 * Short id, unique among the corpus's live inbox entries.
 */
id: string, 
/**
 * When it was captured: RFC 3339 with the offset the stamp was taken
 * at, ending in `Z` when the local offset could not be read. A legacy
 * `YYYY-MM-DDTHH:MM` stamp reads as local time with the offset this
 * machine has for that instant. A stamp that is neither, edited in by
 * hand, is passed through as written.
 */
at: string, 
/**
 * What you wrote.
 */
text: string, };
