// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboxEntry } from "./InboxEntry";

/**
 * Every capture still waiting to be promoted or dropped.
 *
 * Serializes as the bare list, which is the shape `neb inbox --json` has
 * always had.
 */
export type Inbox = Array<InboxEntry>;
