// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A corpus that has just been created.
 */
export type Initialized = { 
/**
 * Where it is.
 */
root: string, };
