// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

/**
 * Nodes matching a filter. Serializes as the bare list.
 */
export type Listing = Array<Node>;
