// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeMigration } from "./NodeMigration";

/**
 * What a migration did.
 */
export type MigrationReport = { 
/**
 * One entry per node that was rewritten, in corpus order. A node already
 * in v2 form is left alone and does not appear.
 */
rewritten: Array<NodeMigration>, 
/**
 * How many nodes were examined.
 */
nodes: number, 
/**
 * Whether `config.yaml` was rewritten.
 */
config_rewritten: boolean, };
