// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Neighbour } from "./Neighbour";

/**
 * The nodes closest to a query, best first. Serializes as the bare list.
 */
export type Near = Array<Neighbour>;
