// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { EdgeRecord } from "./EdgeRecord";
import type { Status } from "./Status";

/**
 * One existing node a query lands near, and how near.
 */
export type Neighbour = { 
/**
 * The node's id.
 */
id: string, 
/**
 * Its one-line title.
 */
title: string, 
/**
 * Where it is in its lifecycle.
 */
status: Status, 
/**
 * Its labels, since a promotion reuses the parent's.
 */
tags: Array<string>, 
/**
 * Lexical similarity in `0..=1`, rounded to three places. Not
 * calibrated: `1` would be a node that saturates every word of the
 * query, which nothing does, and a word-for-word copy of the query
 * scores about `0.35`–`0.6`. [`Band`] is the reading of it.
 */
score: number, 
/**
 * The score read as a coarse band, which is what a human is shown.
 */
band: Band, 
/**
 * The edges already joining this node and the node `near` was asked
 * about, either way round, each once, in declaration order. Null when
 * there are none, which is always the case for a free-text query.
 */
linked: Array<EdgeRecord> | null, };
