// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

/**
 * One existing node a query lands near, and how near.
 */
export type Neighbour = { 
/**
 * The node's id.
 */
id: string, 
/**
 * Its one-line title.
 */
title: string, 
/**
 * Where it is in its lifecycle.
 */
status: Status, 
/**
 * Its labels, since a promotion reuses the parent's.
 */
tags: Array<string>, 
/**
 * Lexical similarity in `0..=1`, rounded to three places. `1` would be a
 * node that saturates every word of the query; anything over about
 * `0.3` shares real vocabulary rather than one incidental word.
 */
score: number, };
