// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Closed } from "./Closed";
import type { Edge } from "./Edge";
import type { Origin } from "./Origin";
import type { Reference } from "./Reference";
import type { Status } from "./Status";

/**
 * One unit of inquiry.
 */
export type Node = { 
/**
 * Kebab-case, permanent, never reused.
 */
id: string, 
/**
 * One line naming the idea.
 */
title: string, 
/**
 * Where it is in its lifecycle.
 */
status: Status, 
/**
 * When it entered the graph.
 */
created: string, 
/**
 * When it last changed.
 */
updated: string, 
/**
 * What would falsify this, written when the hypothesis is stated and
 * before anything is read. This is what keeps the later verdict honest
 * instead of retroactive.
 */
kill?: string | null, 
/**
 * Free-form labels, lowercase kebab-case, normalised on every write.
 * No declared list: `check` warns on drift instead of walling it off.
 */
tags?: Array<string>, 
/**
 * Typed links to other nodes.
 */
edges?: Array<Edge>, 
/**
 * Context, with a note saying why each piece is here.
 */
references?: Array<Reference>, 
/**
 * Why and when it was closed. Only on refuted and abandoned nodes.
 */
closed?: Closed | null, 
/**
 * What produced this node.
 */
origin?: Origin | null, };
