// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node brought forward, and what changed about it.
 */
export type NodeMigration = { 
/**
 * The node's id, which migration never changes.
 */
id: string, 
/**
 * A line per thing that was re-labelled.
 */
notes: Array<string>, };
