// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { Note } from "./Note";

/**
 * One node in full: the frontmatter and the prose.
 */
export type NodeView = { 
/**
 * The structured fields.
 */
node: Node, 
/**
 * The argument, trimmed. Includes the `## Notes` section when one exists.
 */
body: string, 
/**
 * Dated reasoning parsed from the last `## Notes` section, oldest first.
 */
notes?: Array<Note>, };
