// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

/**
 * A node as a graph vertex: what a layout and a label need, nothing else.
 */
export type NodeSummary = { 
/**
 * The node's id.
 */
id: string, 
/**
 * Its one-line title.
 */
title: string, 
/**
 * Where it is in its lifecycle.
 */
status: Status, 
/**
 * Its labels.
 */
tags: Array<string>, 
/**
 * When it entered the graph.
 */
created: string, 
/**
 * When it last changed.
 */
updated: string, };
