// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

/**
 * One node in full: the frontmatter and the prose.
 */
export type NodeView = { 
/**
 * The structured fields.
 */
node: Node, 
/**
 * The argument, trimmed.
 */
body: string, };
