// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A dated paragraph of reasoning appended to a node's body.
 *
 * Notes live in the prose, under a `## Notes` section, not in the
 * frontmatter. This type is the parsed projection that `show --json`
 * exposes; the file itself is still markdown.
 */
export type Note = { 
/**
 * When it was written, as `YYYY-MM-DD`.
 */
at: string, 
/**
 * The reasoning, in the author's words.
 */
text: string, 
/**
 * Who wrote it. A projection rather than a stored field, so this is
 * always stated: the human's line simply does not name an author.
 */
by: string, };
