// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `observatory` reference, located on this machine.
 *
 * The record id is what the corpus stores; the path is what this machine
 * happens to have, and is absent when no root is set or the checkout does
 * not carry the record.
 */
export type ObservatoryLink = { 
/**
 * The reference id within the node, `r1` and up.
 */
reference: string, 
/**
 * The Observatory record id, as stored: `Q002`, `H007`, `R012`.
 */
record: string, 
/**
 * Where that record is, when it resolves under the configured root.
 */
path?: string | null, };
