// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an observatory root came from. `config.yaml` wins over the
 * environment, because it was set on purpose for this corpus.
 */
export type ObservatorySource = "config" | "env" | "unset";
