// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an observatory root came from, in the order the settings win.
 * `Env` and `Machine` are about this machine; `Config` is a path some
 * machine once wrote into the corpus, so it answers only when neither does.
 */
export type ObservatorySource = "env" | "machine" | "config" | "unset";
