// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservatorySource } from "./ObservatorySource";

/**
 * Where `observatory` references resolve, and which setting said so.
 */
export type ObservatoryRoot = { 
/**
 * The Observatory checkout, as it was given. `None` when nothing set it.
 */
root: string | null, 
/**
 * Which of the two settings supplied it.
 */
source: ObservatorySource, };
