// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservatorySource } from "./ObservatorySource";

/**
 * Where `observatory` references resolve, and which setting said so.
 */
export type ObservatoryRoot = { 
/**
 * The Observatory checkout, as it was given. `None` when nothing set it.
 */
root: string | null, 
/**
 * Which setting supplied it.
 */
source: ObservatorySource, 
/**
 * The legacy `observatory_root` key in `config.yaml`, whenever the file
 * still carries one, in effect or not: it is one machine's path in a
 * file every machine shares, so it is worth naming even where a machine
 * setting outranks it.
 */
legacy: string | null, };
