// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing waiting on you.
 */
export type OpenItem = { 
/**
 * The node, or `inbox` for the inbox as a whole.
 */
id: string, 
/**
 * What it is waiting for.
 */
why: string, };
