// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenItem } from "./OpenItem";

/**
 * Nodes that need attention. Serializes as the bare list.
 */
export type OpenReport = Array<OpenItem>;
