// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What produced a node or a reference.
 *
 * Every field is optional, because plenty of ideas genuinely do arrive in the
 * shower and a provenance block that demanded filling would just go unfilled.
 */
export type Origin = { 
/**
 * Orbit task id, e.g. `ORB-11440`.
 */
task?: string | null, 
/**
 * Workspace selector, copied verbatim and never constructed.
 */
workspace?: string | null, 
/**
 * Job run id.
 */
run?: string | null, 
/**
 * Task artifact key holding the output this came from.
 */
artifact?: string | null, 
/**
 * Agent family. Never hardcode one: orbit-research pinned `codex` into
 * its task lookup and the crew names changed underneath it.
 */
agent?: string | null, 
/**
 * When.
 */
at?: string | null, };
