// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";

/**
 * Context attached to a node. The note is the field that matters.
 *
 * `deny_unknown_fields` is what enforces invariant 7: a reference that tries
 * to carry a `verdict` or `strength` fails to parse, so the truth-rating
 * ladder v0.2 removed cannot creep back in through the side door.
 */
export type Reference = { 
/**
 * Unique within the node, never reused.
 */
id: string, 
/**
 * `paper`, `study`, `article`, `note`, `discussion`, `book`, `dataset`,
 * `thread` or `other`.
 */
kind: string, 
/**
 * A URL, DOI, repo path, or almanac wikilink. Discussions may omit it.
 */
uri?: string | null, 
/**
 * Human-readable name.
 */
title?: string | null, 
/**
 * Why this is attached. The only field that still matters in a year.
 */
note?: string | null, 
/**
 * When it was attached.
 */
added: string, 
/**
 * Who attached it and wrote the note. Absent is [`HUMAN`].
 */
by?: string | null, 
/**
 * What produced it.
 */
origin?: Origin | null, };
