// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { UnreadableNode } from "./UnreadableNode";

/**
 * The result of a full check.
 */
export type Report = { 
/**
 * The corpus root checked, with the spelling used to open it.
 */
root: string, 
/**
 * Files and directory entries that could not be loaded.
 */
unreadable: Array<UnreadableNode>, 
/**
 * Everything found, errors first.
 */
findings: Array<Finding>, 
/**
 * How many nodes were examined.
 */
nodes: number, };
