// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which review rule raised a finding.
 */
export type ReviewRule = "stale-hypothesis" | "untouched-seed" | "no-references" | "stale-inbox";
