// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewRule } from "./ReviewRule";

/**
 * One finding from `review`.
 */
export type ReviewItem = { 
/**
 * Which rule raised it.
 */
rule: ReviewRule, 
/**
 * The node, or `inbox`.
 */
id: string, 
/**
 * Its title, or `inbox`.
 */
title: string, 
/**
 * What to look at, and what is proposed.
 */
reason: string, };
