// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewItem } from "./ReviewItem";

/**
 * The weekly maintenance report. Serializes as the bare list of findings.
 */
export type ReviewReport = Array<ReviewItem>;
