// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How badly a finding breaks the corpus.
 *
 * Serialized under the key `level`, which is the name `neb check --json` has
 * always used for it.
 */
export type Severity = "error" | "warn";
