// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle. `seed → hypothesis → refuted | abandoned`.
 */
export type Status = "seed" | "hypothesis" | "refuted" | "abandoned";
