// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";
import type { Status } from "./Status";

/**
 * A node that has moved along its lifecycle.
 */
export type StatusChange = { 
/**
 * The node as written.
 */
doc: Doc, 
/**
 * Where it was before.
 */
from: Status, };
