// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tag and the number of nodes carrying it.
 */
export type TagCount = { 
/**
 * The tag, as it is written on the nodes.
 */
tag: string, 
/**
 * How many nodes carry it.
 */
count: number, };
