// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagCount } from "./TagCount";

/**
 * Every tag in the corpus with a count. Serializes as the bare list.
 */
export type TagCounts = Array<TagCount>;
