// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Via } from "./Via";

/**
 * One node reached from another, and how.
 */
export type Touched = { 
/**
 * The node reached.
 */
id: string, 
/**
 * Which relation reached it.
 */
via: Via, };
