// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeType } from "./EdgeType";

/**
 * One step of a lineage walk: the node it was taken from, and every kind of
 * genealogy edge between the two.
 *
 * The edges are always the descendant's, so the kinds read the same both
 * ways: walking up, `from` is the child that declares them; walking down, it
 * is the ancestor they name. Parallel edges are one step with several kinds.
 */
export type TraceHop = { 
/**
 * The node the step was taken from.
 */
from: string, 
/**
 * The kinds of edge the step followed, in the order declared.
 */
kinds: Array<EdgeType>, };
