// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";
import type { TraceHop } from "./TraceHop";

/**
 * One node on a lineage walk.
 */
export type TraceNode = { 
/**
 * The node's id.
 */
id: string, 
/**
 * Its one-line title.
 */
title: string, 
/**
 * Where it is in its lifecycle.
 */
status: Status, 
/**
 * Its genealogical parents, each once.
 */
parents: Array<string>, 
/**
 * The step that first reached it. Null for the node the walk starts at.
 */
via: TraceHop | null, 
/**
 * The Observatory record it was handed off to, when it was; see
 * [`Node::handed_off_to`]. Omitted otherwise.
 */
handed_off_to?: string | null, };
