// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TraceNode } from "./TraceNode";

/**
 * A lineage walk. Serializes as the bare list of nodes, oldest reachable
 * first, each reported once even when a diamond reaches it twice.
 */
export type Trace = Array<TraceNode>;
