// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

/**
 * One node on a lineage walk.
 */
export type TraceNode = { 
/**
 * The node's id.
 */
id: string, 
/**
 * Its one-line title.
 */
title: string, 
/**
 * Where it is in its lifecycle.
 */
status: Status, 
/**
 * Its genealogical parents.
 */
parents: Array<string>, };
