// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file (or directory entry whose name could not be obtained) a scan
 * could not read. The path is kept as supplied by the corpus root.
 */
export type UnreadableNode = { path: string, code: string, message: string, };
