// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a node in an [`Impact`] is reached.
 */
export type Via = "descends" | "contradicts";
